"""Demo data seeder.

Populates an empty database with a small, realistic knowledge vault so the app
is explorable right after `docker compose up`. Only runs when DEMO_MODE=1 and
the notes table is still empty, so it can never overwrite real data.

Usage:
    python demo_seed.py            # seeds using AGORA_DB_PATH
"""

import os
import sqlite3
import time

from database import DB_PATH, get_db

DEMO_MODE = os.getenv("DEMO_MODE", "0") == "1"

# Notes are (slug, parent_slug, title, pinned, tags, body)
DEMO_NOTES = [
    (
        "root",
        None,
        "Agora Demo Vault",
        1,
        ["start-here"],
        """# Agora Demo Vault

This vault is generated by `backend/demo_seed.py` so that a fresh install has
something to look at. Everything here is fictional.

## What to try

- **Search**: type `rrule` in the search box, it matches inside note bodies.
- **Tags**: click any tag in the sidebar to filter.
- **Wiki links**: [[Agent Workflow]] uses double brackets and shows up as a backlink.
- **Tasks**: see [[Monthly Review]] for checkboxes that can be toggled inline.
- **Graph**: the graph tab renders the link structure of this vault.
- **Export**: `GET /api/export` returns the whole vault as newline-delimited JSON.

## Sections

| Area | Note |
|---|---|
| Agents | [[Agent Workflow]] |
| Finance | [[Monthly Review]] |
| Japanese | [[Study Log]] |
| Travel | [[Kyoto Weekend]] |

> The finance and calendar tabs are pre-loaded with generated demo data too.
""",
    ),
    (
        "agent-workflow",
        "root",
        "Agent Workflow",
        1,
        ["agents", "engineering"],
        """# Agent Workflow

How this repo is maintained by coding agents.

## The ladder

Before writing code, the agent walks down this ladder and stops at the first rung
that applies:

1. Does this need to exist at all? If not, skip it.
2. Is it already in the codebase? Reuse it.
3. Does the standard library already do it?
4. Is there a native platform feature?
5. Is it an installed dependency?
6. Can it be one line?
7. Only then: the minimum that works.

## Rules that never bend

- Validation, error handling, security and accessibility are never cut for brevity.
- Every API-facing change gets a test.
- The agent never edits a file it has not read.

## Why bother

A silent agent with unlimited freedom writes a framework. A constrained agent
writes the ten lines the ticket asked for.

## See also

[[Architecture Decisions]]
""",
    ),
    (
        "architecture-decisions",
        "agent-workflow",
        "Architecture Decisions",
        0,
        ["engineering"],
        """# Architecture Decisions

## ADR 1: SQLite over Postgres

Single-user application, low write volume, and the whole point is that a backup
is one file. `sqlite3` ships with the Python standard library, so there is no
service to run.

Trade-off accepted: no concurrent writers. The WAL journal plus a 5 second busy
timeout keeps the API responsive anyway.

## ADR 2: CSV and JSON in, JSON out

The backend parses upstream CSV exports once and serves clean JSON. The React
frontend never sees a CSV for the finance views, so number formatting and
currency handling live in exactly one place.

## ADR 3: No auth, network isolation instead

The app is designed to run on a private network (Tailscale, LAN) with no
authentication layer in front of it. Anything reachable from the public internet
should sit behind a reverse proxy that terminates TLS and enforces auth.

This is a deliberate trade-off for a personal tool, not an oversight. See the
security notes in the README.
""",
    ),
    (
        "monthly-review",
        None,
        "Monthly Review",
        0,
        ["finance", "habits"],
        """# Monthly Review

## Checklist

- [ ] Export the bank CSV and drop it in the finance data directory
- [x] Reconcile the investment cost basis
- [ ] Update the emergency fund target
- [ ] Review subscriptions

## Savings rate

The dashboard computes the savings rate per month as `(income - expenses) / income`
and averages it across every month that has data. Months with no data are skipped
rather than counted as zero, which would drag the average down.

## Notes

Recurring costs are the ones worth auditing. One-off purchases explain themselves.
""",
    ),
    (
        "study-log",
        None,
        "Study Log",
        0,
        ["japanese"],
        """# Study Log

Parent note for weekly Japanese study entries.

- [[Week 1]]
- [[Week 2]]

## Method

Twenty new cards a day from a frequency deck, plus ten minutes of reading.
Grammar cards are generated from sentences that were actually misread, never
from a generic list.
""",
    ),
    (
        "week-1",
        "study-log",
        "Week 1",
        0,
        ["japanese"],
        """# Week 1

## New vocabulary

| Term | Reading | Meaning |
|---|---|---|
| 図書館 | としょかん | library |
| 約束 | やくそく | promise |
| 準備 | じゅんび | preparation |

## Sentences

- 図書館で本を借りました。
- 約束の時間に遅れないようにします。

## Trouble spots

The passive form still needs drilling.
""",
    ),
    (
        "week-2",
        "study-log",
        "Week 2",
        0,
        ["japanese"],
        """# Week 2

## New vocabulary

| Term | Reading | Meaning |
|---|---|---|
| 経験 | けいけん | experience |
| 相談 | そうだん | consultation |
| 説明 | せつめい | explanation |

## Grammar

- 〜たことがある (past experience)
- 〜ながら (simultaneous actions)

## Listening

Two podcasts, roughly forty minutes, at 0.9x speed.
"""),
    (
        "kyoto-weekend",
        None,
        "Kyoto Weekend",
        0,
        ["travel"],
        """# Kyoto Weekend

## Itinerary

**Day 1**
- Fushimi Inari early, before the crowds
- Nishiki Market for lunch

**Day 2**
- Arashiyama bamboo grove at opening
- Philosopher's Path in the afternoon

## Checklist

- [x] Book the hotel
- [x] Reserve the train seats
- [ ] Check the weather forecast
- [ ] Charge the camera batteries

## Notes

The pass covers the bus network but not the subway. Cash is still faster than
card at the smaller stalls.
""",
    ),
    (
        "rrule-notes",
        None,
        "Recurring Events",
        0,
        ["engineering"],
        """# Recurring Events

The calendar stores a recurrence as one of four plain strings: `daily`, `weekly`,
`monthly`, `yearly`, optionally bounded by a `recurrence_end` date.

Expansion happens at read time. `GET /api/calendar/events?start=&end=` walks each
stored event forward from its original start date until it passes the end of the
requested window, which means a single stored row can produce a year of
occurrences without any background job.

## Skipping one occurrence

`DELETE /api/calendar/events/{id}/occurrences/{date}` appends that date to the
event's `excluded_dates` column instead of deleting the series.

## Why not RRULE

Full RFC 5545 support (intervals, BYDAY, BYSETPOS) is a library-sized problem.
Four keywords cover every event in this vault, and the iCal *export* still emits
compliant `VEVENT` objects, so subscribers on the other end see standard iCal.
""",
    ),
    (
        "backlinks-demo",
        None,
        "Markdown Rendering",
        0,
        ["engineering"],
        """# Markdown Rendering

Notes render live while editing. The renderer is `marked` plus a thin custom
layer for the pieces that matter here.

## What is custom

- Heading anchors, so the table of contents can link into a long note.
- Wiki links: `[[Agent Workflow]]` becomes a link to the target note.
- Task list checkboxes that write back to the API with `PATCH /api/notes/{id}/toggle-task`.

## Two bugs worth remembering

1. Extracting the table of contents from raw markdown picked up `#` lines living
   inside fenced code blocks, so the TOC indices drifted out of step with the
   rendered headings. The fix is to strip fenced blocks before extracting.
2. Scrolling to a heading used `offsetTop` arithmetic, which is relative to the
   nearest positioned ancestor rather than the scroll container. `scrollIntoView`
   gets it right without any maths.

## Links

Back to [[Agent Workflow]].
""",
    ),
    (
        "reading-list",
        None,
        "Reading List",
        0,
        ["reading"],
        """# Reading List

## Currently reading

- *The Design of Everyday Things* — Norman
- *Thinking in Systems* — Meadows

## Queued

- *A Philosophy of Software Design* — Ousterhout
- *The Pragmatic Programmer* — Hunt, Thomas

## Finished

| Title | Rating | Note |
|---|---|---|
| Refactoring | 5 | Second edition is worth it for the examples alone |
| The Mythical Man-Month | 4 | Dated in places, still sharp on estimation |
""",
    ),
    (
        "clip-template",
        None,
        "Web Clipping",
        0,
        ["engineering"],
        """# Web Clipping

`POST /api/clip` fetches a page, strips navigation and scripts, and creates a
note from the remaining text.

## Guards

- Only `http` and `https` schemes are accepted.
- The hostname is resolved before the request; anything resolving to a private,
  loopback, or link-local address is rejected. That closes the obvious
  server-side request forgery hole.
- Redirects are followed manually, at most three of them, and each hop is
  re-validated through the same check.
- The fetch has a ten second timeout.

## Why manual redirects

`requests` follows redirects before you get a chance to inspect the target, which
is exactly how a public URL turns into a request to `169.254.169.254`.
""",
    ),
]

# Calendar events: (slug, title, start_offset_days, duration_days, all_day,
#                   time, color, recurrence, recurrence_end, location, description)
DEMO_EVENTS = [
    ("standup", "Team standup", -21, 0, False, "09:30", "#06b6d4", "weekly", None, "Video call", "Fifteen minutes, blockers only"),
    ("gym", "Gym", -14, 0, False, "19:00", "#00c49f", "weekly", None, "Neighbourhood gym", "Push day"),
    ("rent", "Rent due", -5, 0, True, None, "#f7931a", "monthly", None, None, "Standing transfer"),
    ("review", "Monthly finance review", 3, 0, False, "20:00", "#d4af37", None, None, "Home", "Reconcile the CSV exports"),
    ("dentist", "Dentist", 6, 0, False, "15:00", "#f43f5e", None, None, "Clinic", "Six month check"),
    ("trip", "Kyoto weekend", 12, 2, True, None, "#8884d8", None, None, "Kyoto", "See the travel note"),
    ("conference", "Conference talk", 27, 0, False, "10:00", "#627eea", None, None, "Online", "Forty minutes plus questions"),
    ("birthday", "Birthday dinner", 33, 0, False, "19:30", "#fb923c", None, None, "Restaurant", "Booked for six"),
    ("deepwork", "Deep work block", 1, 0, False, "08:00", "#9ca3af", "daily", None, "Home office", "No meetings"),
]

NOW = int(time.time())
DAY = 86400

# Bounded recurrences: without an end date a daily event expands across the whole
# requested range, which makes any long calendar query enormous.
RECURRENCE_END_DAYS = {"daily": 30, "weekly": 84, "monthly": 365, "yearly": 730}


def _note_id(slug: str) -> str:
    return f"note-demo-{slug}"


def seed_demo_data(db_path: str = DB_PATH) -> int:
    """Insert demo notes and events. Returns the number of notes inserted."""
    with get_db() as conn:
        existing = conn.execute("SELECT COUNT(*) AS n FROM notes").fetchone()["n"]
        if existing:
            return 0

        for idx, (slug, parent, title, pinned, tags, body) in enumerate(DEMO_NOTES):
            created = NOW - (len(DEMO_NOTES) - idx) * DAY
            conn.execute(
                """INSERT INTO notes (id, folder_id, parent_id, title, body, created_at, updated_at, pinned)
                   VALUES (?, NULL, ?, ?, ?, ?, ?, ?)""",
                (
                    _note_id(slug),
                    _note_id(parent) if parent else None,
                    title,
                    body,
                    created,
                    created + 3600,
                    pinned,
                ),
            )
            for name in tags:
                tag_id = f"tag-demo-{name}"
                conn.execute(
                    "INSERT OR IGNORE INTO tags (id, name, created_at) VALUES (?, ?, ?)",
                    (tag_id, name, created),
                )
                conn.execute(
                    "INSERT OR IGNORE INTO note_tags (note_id, tag_id) VALUES (?, ?)",
                    (_note_id(slug), tag_id),
                )

        for idx, ev in enumerate(DEMO_EVENTS):
            slug, title, offset, duration, all_day, start_time, color, rec, rec_end, location, desc = ev
            start = time.strftime("%Y-%m-%d", time.localtime(NOW + offset * DAY))
            end = time.strftime("%Y-%m-%d", time.localtime(NOW + (offset + duration) * DAY))
            if rec and not rec_end:
                rec_end = time.strftime(
                    "%Y-%m-%d", time.localtime(NOW + (offset + RECURRENCE_END_DAYS[rec]) * DAY)
                )
            conn.execute(
                """INSERT INTO calendar_events
                   (id, title, start_date, end_date, all_day, color, description, location,
                    recurrence, recurrence_end, original_date, created_at, updated_at,
                    start_time, end_time, excluded_dates)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, NULL)""",
                (
                    f"event-demo-{slug}",
                    title,
                    start,
                    end,
                    1 if all_day else 0,
                    color,
                    desc,
                    location,
                    rec,
                    rec_end,
                    NOW,
                    NOW,
                    start_time,
                    None if not start_time else f"{int(start_time.split(':')[0]) + 1:02d}:{start_time.split(':')[1]}",
                ),
            )

        conn.commit()
        return len(DEMO_NOTES)


def maybe_seed(db_path: str = DB_PATH) -> None:
    """Seed only when demo mode is on and the database is empty."""
    if not DEMO_MODE:
        return
    try:
        inserted = seed_demo_data(db_path)
    except sqlite3.Error as exc:  # pragma: no cover - startup path
        print(f"[demo_seed] skipped: {exc}")
        return
    if inserted:
        print(f"[demo_seed] inserted {inserted} demo notes and {len(DEMO_EVENTS)} demo events")


if __name__ == "__main__":
    count = seed_demo_data()
    print(f"seeded {count} notes" if count else "database already has notes, nothing to do")
